#!/bin/ash

SUFIX=hosts
SUFIX2=rule

lsmod | grep hwf_kproxy >/dev/null
if [ $? -ne 0 ]; then
  exit 0;
fi

add_host_by_file()
{
  kproxy-init add $1
}

del_host_by_file()
{
  kproxy-init del $1
}
  
case $1 in
  init)
    for file in `ls /etc/kproxy.d/*.$SUFIX 2>/dev/null`; do
      add_host_by_file $file
    done

    for file in `ls /etc/kproxy.d/*.$SUFIX2 2>/dev/null`; do
      kproxy-file add $file
    done    
  ;;

  install)
    shift
    until [ $# -eq 0 ]; do
        if [ -e /etc/kproxy.d/$1.$SUFIX ]; then
            add_host_by_file /etc/kproxy.d/$1.$SUFIX
        fi
        if [ -e /etc/kproxy.d/$1.$SUFIX2 ]; then
            kproxy-file add /etc/kproxy.d/$1.$SUFIX2
        fi      
        shift
    done
  ;;

  uninstall)
    shift
    until [ $# -eq 0 ]; do
        if [ -e /etc/kproxy.d/$1.$SUFIX ]; then
            del_host_by_file /etc/kproxy.d/$1.$SUFIX
        fi
        if [ -e /etc/kproxy.d/$1.$SUFIX2 ]; then
            kproxy-file del /etc/kproxy.d/$1.$SUFIX2
        fi       
        shift
    done
  ;;

  *)
    echo "Usage: kproxy-conf [install|uninstall] <app-name>"
  ;;
esac

