#!/bin/sh
#
# Copyright (C) 2012-2014 www.hiwifi.com
#

. /etc/functions.sh
. /lib/ralink.sh
. /lib/functions/uci-defaults.sh

hiwifi_storage_setup() {
	local board="$1"
	case $board in
	"HC5663" | "BL-H750AC")
		ucidef_set_storage "DISK" "3000M"
		;;
	"HC5661" | "HC5761" | "HB5881")
		ucidef_set_storage "SD" "3000M"
		;;
	*)
		ucidef_set_storage "NULL" "0M"
		;;
	esac
}

[ -e /etc/config/hiwifi ] && exit 0

touch /etc/config/hiwifi

board=$(tw_board_name)

hiwifi_storage_setup $board

uci commit hiwifi

exit 0
