#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=51

SERVICE_USE_PID=1

start () {
	move_from_keep

	loglevel=$(uci get system.@system[0].cronloglevel &>/dev/null)
	[ -z "$(ls /etc/crontabs/)" ] && exit 1
	mkdir -p /var/spool/cron
	ln -s /etc/crontabs /var/spool/cron/ 2>/dev/null
	service_start /usr/sbin/crond -c /etc/crontabs -l ${loglevel:-9}
}

stop() {
	service_stop /usr/sbin/crond
}

move_from_keep() {
	cp /rom/etc/crontabs/root /etc/crontabs/root
}

