#!/bin/sh /etc/rc.common
# Copyright (c) 2012 Elite Co., Ltd.
# Copyright (c) 2012 LIKAI <9@kai.li>

START=70
STOP=30

start() {
	/usr/bin/spawn-fcgi -s /var/run/fcgi-cgi.sock -u root -U nobody -- /usr/bin/fcgi-cgi
}

stop () {
	killall fcgi-cgi
}
