#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=22

FW_LIBDIR=/lib/firewall
LOCK_TAG=firewall

fw() {
	. $FW_LIBDIR/core.sh
	fw_$1
}

start() {
	fw start
}

stop() {
	fw stop
}

restart() {
	fw restart
}

reload() {
	fw reload
}
