#!/bin/sh /etc/rc.common

START=41
STOP=59

start() {
  [ "$(cat /etc/nginx/mode 2>/dev/null)" == "normal" ] && {
    return 
  }
  insmod kjson
  insmod kmultifast
  insmod hwf_kproxy
  lan_ipaddr=$(uci get network.lan.ipaddr)
  kproxy -A -A ${lan_ipaddr}:81
  kproxy-conf init
}

stop() {
  rmmod hwf_kproxy
  rmmod kmultifast
  rmmod kjson
}

