#!/bin/sh /etc/rc.common

. /etc/kproxy.common

START=41
STOP=59

start() {
  [ "$(cat /etc/nginx/mode 2>/dev/null)" == "normal" ] && {
    return 
  }

  if [ -f /etc/kproxy.priority ]; then
  	source /etc/kproxy.priority > /dev/null 2>&1
  fi
  
  insmod kjson
  insmod kmultifast

  if expr $priority : '-\?[1-9][0-9]*$' > /dev/null 2>&1; then
    insmod hwf_kproxy hwf_kproxy_hook_priority=$priority
  else
    insmod hwf_kproxy
  fi
  
  lan_ipaddr=$(uci get network.lan.ipaddr)
  kproxy_addrport_add ${lan_ipaddr} 81 0
  kproxy-conf init
}

stop() {
  rmmod hwf_kproxy
  rmmod kmultifast
  rmmod kjson
}

