#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2010 OpenWrt.org

#START=60
BIN=xl2tpd
DEFAULT=/etc/default/$BIN
RUN_D=/var/run
PID_F=$RUN_D/$BIN.pid

start() {
	mkdir -p $RUN_D/$BIN
	[ -f $DEFAULT ] && . $DEFAULT
	$BIN $OPTIONS
}

stop() {
	[ ! -f $PID_F ] && return 0
	pid=$(cat $PID_F)
	kill $pid
	while [ -n "$(cat /proc/$pid/stat 2>/dev/null | grep $BIN)" ];do sleep 1;done
}
