#!/bin/sh /etc/rc.common

stop()
{
	if [ "$TYPE" -ne "0" ];then
		if [ "dhcp" = "$(uci get network.wan.proto)" ];then
			kill -USR2 $(pidof udhcpc)
		fi
	fi
}

start()
{
	if [ "$TYPE" -ne "0" ];then
		if [ "dhcp" = "$(uci get network.wan.proto)" ];then
			kill -USR1 $(pidof udhcpc)
		fi
	fi
}
