#!/bin/sh

INCLUDE_FILE=$1
FUNCTION=$2

. $INCLUDE_FILE
type $FUNCTION | grep 'function' &> /dev/null
if [ $? -eq 0 ]; then
  $FUNCTION
else
  echo "No predefined function $FUNCTION in $INCLUDE_FILE."
  exit 1
fi
