#!/bin/sh /etc/rc.common
# Copyright (C) 2012-2013 HiWiFi Co., Ltd
srcdir=/var/log
src=$srcdir/syslog
dstdir=/tmp/data/log
dst=$dstdir/syslog
max_file_count=25


rotate() {
	local file is_boot_stage=1
	for file in $(ls $src.* 2>/dev/null)
	do
		is_boot_stage=0
		mv $file $dst.$(date +%Y%m%d%H%M%S).$(echo ${file#*.})
	done
	[ $is_boot_stage -eq 1 ] && mv $dst $dst.$(date +%Y%m%d%H%M%S)
	ls -t $dst.* 2>/dev/null | sed "1,${max_file_count}d" | xargs rm -rf
}

start() {
	stop
	if [ -L /tmp/data ];then
		mkdir -p $dstdir
		rotate
		cp -f $src $dst
		tail -f $src >> $dst 2>/dev/null &
	fi
}

stop() {
	local ret
	ret=$(ps | grep "[t]ail -f $src")
	if [ $? -eq 0 ];then
		kill $(echo $ret | awk '{print $1}') 2>/dev/null
	fi
}

restart() {
	stop
	start
}
